[package]
name = "tenkan"
version = "0.1.3"
edition = "2024"
description = "Convert .env files to c headers"
repository = "https://github.com/pirsonxyz/tenkan"
authors = ["Pirson Bethancourt", "pirson@pirson.xyz"]
keywords = ["c", "embedded", "cpp"]
license = "MIT"

[dependencies]

